### ISSUE TITLE
CMPclient-embedded-lib sub-folder is empty

### ISSUE THREAD

**Issue by harmin-parra** [nokia/CMPclient-embedded-lib#1]
When executing git clone, or downloadind the ZIP file, I realize that the CMPclient-embedded-lib sub-folder is empty.

As a consequence, when I execute make, the compilation fails because the file cmpcl.h is missing.

**Comment by mpeylo** [comment]
I speculate that this issue is actually for the CMPclient-embedded repository? How to download is described in the [README.md](https://github.com/nokia/CMPclient-embedded/blob/master/README.md) as follows, let me know if it doesn't work. If you download the ZIP there should be some way to download submodules afterwards.


> **Download**
> 
> If the code is cloned from GitHub, one might prefer to use the --recurse flag to immeditaly also clone the CMPclient library and Mbed TLS which are referenced as git submodules.
> 
> $ git clone --recursive https://github.com/nokia/CMPclient-embedded.git
> 
>
